pipeline:
  build:
    image: node
    commands:
      - npm install
  publish:
    image: plugins/docker
    repo: registry.paradas.co/drone/rafa-crypto-bot
    registry: registry.paradas.co
    secrets: [docker_username, docker_password]
    tags:
      - latest
      - build-${DRONE_BUILD_NUMBER}
